sudo: false

language: scala
jdk:
- openjdk11

branches:
  only:
  - master

services:
  - docker

env:
  MVN_VERSION="3.6.0"

before_install:
  - curl https://archive.apache.org/dist/maven/maven-$(echo $MVN_VERSION | cut -d '.' -f1)/$MVN_VERSION/binaries/apache-maven-$MVN_VERSION-bin.tar.gz | tar -xzv -C /tmp
  - export M2_HOME=/tmp/apache-maven-$MVN_VERSION
  - export PATH=$M2_HOME/bin:$PATH

jobs:
  include:
    - stage: Tests
      name: "Unit tests"
      script: mvn test
    - name: "Integration tests"
      script: ets-kafka-topic-config-manager-example/run.sh
